<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Scheme;

class SchemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schemes = [
            ['name' => 'Supporting Staff Produksi Vaksin BCG', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin BCG', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin BCG', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin BCG', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Vaksin Difteri', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin Difteri', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin Difteri', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin Difteri', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Vaksin Tetanus', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin Tetanus', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin Tetanus', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin Tetanus', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Vaksin HiB', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin HiB', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin HiB', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin HiB', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Vaksin Pertusis', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin Pertusis', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin Pertusis', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin Pertusis', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi OPV', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi OPV', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi OPV', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi OPV', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Vaksin Campak', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Vaksin Campak', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Vaksin Campak', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Vaksin Campak', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi nOPV', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi nOPV', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi nOPV', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi nOPV', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Bulk Virus Multiproduk', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Bulk Virus Multiproduk', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Bulk Virus Multiproduk', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Bulk Virus Multiproduk', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Media', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Media', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Formulasi Pengisian Vaksin 2', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Formulasi Pengisian Vaksin 2', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Formulasi Pengisian Vaksin 2', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Formulasi Pengisian Vaksin 2', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Formulasi Pengisian Vaksin 1', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Formulasi Pengisian Vaksin 1', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Formulasi Pengisian Vaksin 1', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Formulasi Pengisian Vaksin 1', 'scope' => 'Produksi'],
            ['name' => 'Supporting Staff Produksi Pengemasan', 'scope' => 'Produksi'],
            ['name' => 'Operation Staff Produksi Pengemasan', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Pengemasan', 'scope' => 'Produksi'],
            ['name' => 'Manager Assistant Produksi Pengemasan', 'scope' => 'Produksi'],
            ['name' => 'Kepala Divisi Surveilans dan Riset Klinis', 'scope' => 'SRK'],
            ['name' => 'Kepala Departemen Surveilans dan Epidemiologi', 'scope' => 'SRK'],
            ['name' => 'Manager Surveilans dan Epidemiologi', 'scope' => 'SRK'],
            ['name' => 'Kepala Departemen Uji Klinis', 'scope' => 'SRK'],
            ['name' => 'Manager Uji Klinis', 'scope' => 'SRK'],
            ['name' => 'Kepala Departemen Farmakovigilans', 'scope' => 'SRK'],
            ['name' => 'Manager Farmakovigilans', 'scope' => 'SRK'],
            ['name' => 'Pelaksana Pengujian Mutu Kimia Fisika', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Kimia Fisika Produk Biopharmaceutical', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Bahan Baku dan Penunjang', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Bahan Kemasan', 'scope' => 'QC'],
            ['name' => 'Kepala Departemen Pengujian Mutu Kimia Fisika', 'scope' => 'QC'],
            ['name' => 'Pelaksana Pengujian Mutu Mikrobiologi', 'scope' => 'QC'],
            ['name' => 'Manager Sterilitas dan Pemantauan Mikroba', 'scope' => 'QC'],
            ['name' => 'Manager Validasi Mikrobiologi', 'scope' => 'QC'],
            ['name' => 'Manager Monitoring Lingkungan', 'scope' => 'QC'],
            ['name' => 'Manager Monitoring Air, Bahan Baku dan Produk', 'scope' => 'QC'],
            ['name' => 'Kepala Departemen Pengujian Mutu Mikrobiologi', 'scope' => 'QC'],
            ['name' => 'Pelaksana Pengujian Mutu Vaksin Virus', 'scope' => 'QC'],
            ['name' => 'Staf Muda IPC Campak Rubella, IPC Polio dan Rota Virus, Potensi Cell Based Assay', 'scope' => 'QC'],
            ['name' => 'Staf IPC Campak Rubella, IPC Polio dan Rota Virus, Potensi Cell Based Assay', 'scope' => 'QC'],
            ['name' => 'Staf IPC Influenza, Hepatitis dan Biosimilar, Potensi Immunological Assay', 'scope' => 'QC'],
            ['name' => 'Manager IPC Campak Rubella, IPC Polio dan Rota Virus, Potensi Cell Based Assay', 'scope' => 'QC'],
            ['name' => 'Manager IPC Influenza, Hepatitis dan Biosimilar, Potensi Immunological Assay', 'scope' => 'QC'],
            ['name' => 'Kepala Departemen Pengujian Mutu Vaksin Virus', 'scope' => 'QC'],
            ['name' => 'Pelaksana Patologi dan Toksikologi', 'scope' => 'QC'],
            ['name' => 'Staf Muda Pengujian Neurovirulence dan Extraneous Agent', 'scope' => 'QC'],
            ['name' => 'Staf Muda Patologi dan In Vivo Potensi', 'scope' => 'QC'],
            ['name' => 'Staf Muda Uji Keamanan dan Toksisitas Abnormal', 'scope' => 'QC'],
            ['name' => 'Staf Patologi, In Vivo Potensi, Neurovirulence dan Extraneous Agent (PIPV dan NVT)', 'scope' => 'QC'],
            ['name' => 'Staf Health Monitoring, Uji Keamanan dan Toksisitas Abnormal (F)', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Neurovirulence dan Extraneous Agent', 'scope' => 'QC'],
            ['name' => 'Manager Health Monitoring', 'scope' => 'QC'],
            ['name' => 'Manager Patologi dan In Vivo Potensi', 'scope' => 'QC'],
            ['name' => 'Manager Uji Keamanan dan Toksisitas Abnormal', 'scope' => 'QC'],
            ['name' => 'Kepala Departemen Patologi dan Toksikologi', 'scope' => 'QC'],
            ['name' => 'Pelaksana Pengujian Mutu Vaksin Bakteri', 'scope' => 'QC'],
            ['name' => 'Staf Muda Pengujian Potensi dan Toksisitas', 'scope' => 'QC'],
            ['name' => 'Staf Pengujian Vaksin BCG dan In vitro', 'scope' => 'QC'],
            ['name' => 'Staf Pengujian Potensi, Toksisitas dan In Vitro', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Vaksin BCG', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian In Vitro', 'scope' => 'QC'],
            ['name' => 'Manager Pengujian Potensi dan Toksisitas', 'scope' => 'QC'],
            ['name' => 'Kepala Departemen Pengujian Mutu Vaksin Bakteri', 'scope' => 'QC'],
            ['name' => 'Kepala Divisi Pengawasan Mutu', 'scope' => 'QC'],
            ['name' => 'Supporting Staff Penelitian dan Pengembangan', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Kimia Fisika Routine Analysis and Validation', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Kimia Fisika Routine Analysis and Validation', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Biologi Routine Analysis and Validation', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Biologi Routine Analysis and Validation', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Routine Analysis and Validation', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Analytical Development', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Pre Klinis', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Pre Klinis', 'scope' => 'Litbang'],
            ['name' => 'Senior Researcher Coordinator Penelitian dan Pengembangan', 'scope' => 'Litbang'],
            ['name' => 'Kepala Divisi Penelitian dan Pengembangan', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Diagnostik', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Live Attenuated Vaccine', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Translasi Produk Rekombinan Sediaan Liquid', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Pengembangan Translasi Produk Rekombinan Sediaan Liquid', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Translasi Produk Rekombinan Sediaan Freeze Dry', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Pengembangan Translasi Produk Rekombinan Berbasis Sel Mamalia', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Inactivated Vaccine', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Inactivated Vaccine', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Live Attenuated Vaccine (LAV)', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Live Attenuated Vaccine (LAV)', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Antibody Drug Conjugate (ADC)', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Antibody Drug Conjugate (ADC)', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator USP Pengembangan Produk Bio Terapeutik Dan Vaksin', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator DSP Pengembangan Produk Bio Terapeutik', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating DSP Pengembangan Vaksin Sub Unit', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Vaksin Sub Unit', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator DSP Pengembangan Vaksin Sub Unit', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating DSP Pengembangan Produk Vaksin Whole Pathogen', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Produk Vaksin Whole Pathogen', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator DSP Pengembangan Produk Vaksin Whole Pathogen', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Formulation Pengembangan Produk Sediaan Liquid', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Formulation Pengembangan Produk Sediaan Liquid', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Formulation Pengembangan Produk Sediaan Liquid', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Formulation Pengembangan Produk Sediaan Freeze Dry', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Formulation Pengembangan Produk Sediaan Freeze Dry', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Formulation Pengembangan Produk Sediaan Freeze Dry', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Pengembangan Produk Multivalent (Witnes)', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Pengembangan Produk Multivalent (Witnes)', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Pengembangan Produk Multivalent', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Freeze Dry Pengembangan Produk Multivalent', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Freeze Dry Pengembangan Produk Multivalent', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Freeze Dry Pengembangan Produk Multivalent', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Process Preparation Pengembangan Produk Bio Terapeutik dan Vaksin', 'scope' => 'Litbang'],
            ['name' => 'Senior Researcher Coordinator Transfer Project', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Regulatory Compliance', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Regulatory Compliance', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Regulatory Compliance', 'scope' => 'Litbang'],
            ['name' => 'Researcher Sub Coordinator Transfer Project', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Transfer Project', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Transfer Project', 'scope' => 'Litbang'],
            ['name' => 'Kepala Departemen Infrastruktur Riset', 'scope' => 'Litbang'],
            ['name' => 'Manajer Fasilitas Infrastruktur Riset', 'scope' => 'Litbang'],
            ['name' => 'Staf Fasilitas Infrastruktur Riset', 'scope' => 'Litbang'],
            ['name' => 'Supporting Staff Fasilitas Infrastruktur Riset', 'scope' => 'Litbang'],
            ['name' => 'Manajer Peralatan Lab Riset', 'scope' => 'Litbang'],
            ['name' => 'Manajer Peralatan Mesin dan Utilitas Riset', 'scope' => 'Litbang'],
            ['name' => 'Staf Peralatan Mesin dan Utilitas Riset', 'scope' => 'Litbang'],
            ['name' => 'Supporting Staff Peralatan Mesin dan Utilitas Riset', 'scope' => 'Litbang'],
            ['name' => 'Kepala Departemen Produksi Vaksin BCG', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Vaksin Difteri', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Vaksin Tetanus', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Vaksin HiB', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Vaksin Pertusis', 'scope' => 'Produksi'],
            ['name' => 'Kepala Divisi Produksi Vaksin Bakteri', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi OPV', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Vaksin Campak', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi nOPV', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Bulk Virus Multiproduk', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Media', 'scope' => 'Produksi'],
            ['name' => 'Kepala Divisi Produksi Vaksin Virus', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Formulasi Pengisian Vaksin 2', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Formulasi Pengisian Vaksin 1', 'scope' => 'Produksi'],
            ['name' => 'Kepala Departemen Produksi Pengemasan', 'scope' => 'Produksi'],
            ['name' => 'Kepala Divisi Produksi Farmasi', 'scope' => 'Produksi'],
            ['name' => 'Staf Muda Surveilans dan Epidemiologi', 'scope' => 'SRK'],
            ['name' => 'Staf Uji Klinis', 'scope' => 'SRK'],
            ['name' => 'Staf Muda Uji Klinis', 'scope' => 'SRK'],
            ['name' => 'Staf Farmakovigilans', 'scope' => 'SRK'],
            ['name' => 'Staf Muda Pengujian Kimia Fisika Produk Biopharmaceutical', 'scope' => 'QC'],
            ['name' => 'Staf Muda Pengujian Bahan Baku dan Penunjang', 'scope' => 'QC'],
            ['name' => 'Staf Muda Pengujian Bahan Kemasan', 'scope' => 'QC'],
            ['name' => 'Staf Pengujian Kimia Fisika', 'scope' => 'QC'],
            ['name' => 'Staf Muda Sterilitas dan Pemantauan Mikroba', 'scope' => 'QC'],
            ['name' => 'Staf Muda Validasi Mikrobiologi', 'scope' => 'QC'],
            ['name' => 'Staf Muda Monitoring Lingkungan', 'scope' => 'QC'],
            ['name' => 'Staf Muda Monitoring Air, Bahan Baku dan Produk', 'scope' => 'QC'],
            ['name' => 'Staf Pengujian Mutu Mikrobiologi', 'scope' => 'QC'],
            ['name' => 'Staf Muda IPC Influenza, Hepatitis dan Biosimilar, Potensi Immunological Assay', 'scope' => 'QC'],
            ['name' => 'Staf Muda Health Monitoring', 'scope' => 'QC'],
            ['name' => 'Operation Staff Produksi Media', 'scope' => 'Produksi'],
            ['name' => 'Officer Produksi Media', 'scope' => 'Produksi'],
            ['name' => 'Staf Muda Pengujian Vaksin BCG', 'scope' => 'QC'],
            ['name' => 'Staf Muda Pengujian In Vitro', 'scope' => 'QC'],
            ['name' => 'Assistant Researcher QC Development', 'scope' => 'QC'],
            ['name' => 'Assistant Researcher Diagnostik', 'scope' => 'QC'],
            ['name' => 'Assistant Researcher USP Penelitian dan Pengembangan', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Translasi Produk Rekombinan Sediaan Freeze Dry', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Translasi Produk Rekombinan Berbasis Sel Mamalia', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating USP Pengembangan Produk Bio Terapeutik Dan Vaksin', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating DSP Pengembangan Produk Bio Terapeutik', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher DSP Pengembangan Produk Bio Terapeutik', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Operating Preparation Pengembangan Produk Bio Terapeutik dan Vaksin', 'scope' => 'Litbang'],
            ['name' => 'Assistant Researcher Preparation Pengembangan Produk Bio Terapeutik dan Vaksin', 'scope' => 'Litbang'],
            ['name' => 'Staf Peralatan Lab Riset', 'scope' => 'Litbang'],
            ['name' => 'Supporting Staff Peralatan Lab Riset', 'scope' => 'Litbang'],
            ['name' => 'General Manager Produksi', 'scope' => 'Pharmaceutical'],
            ['name' => 'General Manager Quality Control', 'scope' => 'Pharmaceutical'],
            ['name' => 'General Manager Quality Assurance', 'scope' => 'Pharmaceutical'],
            ['name' => 'General Manager Research and Development', 'scope' => 'Pharmaceutical'],
            ['name' => 'Plant Manager', 'scope' => 'Pharmaceutical'],
            ['name' => 'Manager Produksi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Manager Pemastian Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Manager Pengawasan Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Manager Research and Development', 'scope' => 'Pharmaceutical'],
            ['name' => 'Manager Regulatory Affair', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Industri', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Pelayanan Apotek', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Distribusi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Industri Pengawasan Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Industri Pemastian Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Industri Produksi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Apoteker Research and Development', 'scope' => 'Pharmaceutical'],
            ['name' => 'Assistant Manager Produksi Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Assistant Manager Produksi Non Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Assistant Manager Pemastian Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Assistant Manager Penunjang Teknis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Vigilans Affair', 'scope' => 'Pharmaceutical'],
            ['name' => 'Assistant Manager Pengawasan Mutu', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengolahan Produk Solid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengolahan Kapsul Lunak & Suppositoria', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengolahan Produk Larutan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengolahan Produk Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Produk Pengolahan Semi Solid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengolahan Produk Betalaktam', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengemasan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Sistem Mutu Proses', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Kalibrasi dan Kualifikasi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Penunjang Teknis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Sistem Mutu Post Market', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Stabilitas', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Validasi Proses dan Pembersihan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Validasi Metode Analisis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengujian Bahan Baku', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengujian Produk', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor Pengujian Mikrobiologi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Supervisor In Process Control', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Formulasi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Packaging', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Analisis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Stabilitas', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Sintesis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Rapid Test', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Natural Extract', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Consumer Research', 'scope' => 'Pharmaceutical'],
            ['name' => 'Dossier Development', 'scope' => 'Pharmaceutical'],
            ['name' => 'Peneliti Mikrobiologi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Regulatory Affair', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Granulasi Basah', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Granulasi Kering', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pengeringan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Final Mixing', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pencetakan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Penyalutan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pengolahan Kapsul Lunak', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Filling Kapsul', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pengolahan Produk Suppositoria', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Mixing Produk Liquid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Filling Produk Liquid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Mixing Produk Semisolid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Filling Produk Semisolid', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Mixing Produk Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Filling Produk Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pencucian dan Sterilisasi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Blistering', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Stripping', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Sacheting', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Counting', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pengemasan dengan Labeling', 'scope' => 'Pharmaceutical'],
            ['name' => 'Operator Pengemasan dengan Tanpa Labeling', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Validasi Proses', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Validasi Analisis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Kalibrasi dan Kualifikasi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Product Quality Review', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Batch Production Release', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Stabilitas', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Compliance', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Dokumen Management System', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Penunjang Teknis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Sampling Bahan Baku', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Bahan Baku', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Bahan Kemas Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Bahan Kemas Non Steril', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Produk', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Mikrobiologi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Monitoring Lingkungan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Pengujian Mikrobiologi, Sterilitas dan Endotoksin', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana In Process Control', 'scope' => 'Pharmaceutical'],
            ['name' => 'Pelaksana Desain Kemasan', 'scope' => 'Pharmaceutical'],
            ['name' => 'Asisten Peneliti Formulasi', 'scope' => 'Pharmaceutical'],
            ['name' => 'Asisten Peneliti Sintesis', 'scope' => 'Pharmaceutical'],
            ['name' => 'Asisten Peneliti Rapid Test', 'scope' => 'Pharmaceutical'],
            ['name' => 'Asisten Peneliti Natural Extract', 'scope' => 'Pharmaceutical'],
            ['name' => 'Asisten Peneliti Pengujian Mikrobiologi', 'scope' => 'Pharmaceutical'],
        ];

        foreach ($schemes as $scheme) {
            Scheme::create($scheme);
        }
    }
}
